### ISSUE TITLE
安全性問題

### ISSUE THREAD

**Issue by kanboo** [ReactMaker/simple_react_start_kit#45]
你好：

我今天使用 simple_react_start_kit 的範本，然後上傳至github後，

有提醒我下列的問題，不知安裝新版的 hoek 後，是否需要調整什麼設定呢？

如：webpack

Known moderate severity security vulnerability detected in hoek < 4.2.1defined in package-lock.json.
--
package-lock.json update suggested: hoek ~> 4.2.1.

**Comment by chnbohwr** [comment]
node-sass 他們要等 v5 大版進了才會解決，所以我先 fork 一個出來改。 目前已修正
